django/gnbproject/urls.py
# from django.contrib import admin
# from gnb import views
from baton.autodiscover import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
import notifications.urls
import gnb.views

urlpatterns = [
    path("", gnb.views.frontend_view, name="index"),
    path("gnb/contact/", gnb.views.contact_view, name="contact_view"),
    path("gnb/expenses/", gnb.views.get_expenses_view, name="get_expenses_view"),
    path(
        "gnb/expenses/<int:expense_sheet_id>/",
        gnb.views.get_expense_sheet_view,
        name="get_expense_sheet_view",
    ),
    path("gnb/invoices/", gnb.views.get_invoices_view, name="get_invoices_view"),
    path(
        "gnb/invoices/<int:invoice_id>/",
        gnb.views.get_invoice_view,
        name="get_invoice_view",
    ),
    path("gnb/report_users/", gnb.views.users_report_view, name="users_report_view"),
    path(
        "gnb/report_projects/",
        gnb.views.projects_report_view,
        name="projects_report_view",
    ),
    path("gnb/new_cashin/", gnb.views.new_cashin_view, name="new_cashin_view"),
    path("gnb/new_project/", gnb.views.new_project_view, name="new_project_view"),
    path(
        "gnb/projects/<str:project_code>", gnb.views.project_view, name="project_view"
    ),
    path(
        "gnb/projects/<str:project_code>/new_invoice/",
        gnb.views.new_invoice_view,
        name="new_invoice_view",
    ),
    path(
        "gnb/projects/<str:project_code>/new_expense/",
        gnb.views.new_expense_view,
        name="new_expense_view",
    ),
    path("gnb/new_user/", gnb.views.new_user_view, name="new_user_view"),
    path("gnb/dashboard/", gnb.views.my_dashboard_view, name="my_dashboard_view"),
    path("admin/", admin.site.urls),
    path("accounts/", include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("baton/", include("baton.urls")),
    path("odoo/", include("odoo.urls")),
    path(
        "inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path("__debug__/", include("debug_toolbar.urls")),
]
# urlpatterns += static("api/media/", document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import os.path

    # settings.STATICFILES_DIRS += os.path.join(settings.BASE_DIR, "frontend","static"),
    # print('settings.STATICFILES_DIRS', settings.STATICFILES_DIRS)
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    FRONTEND_URL = "/static/"
    FRONTEND_ROOT_STATIC = os.path.join(settings.BASE_DIR, "gnb", "static")
    print("FRONTEND_ROOT_STATIC", FRONTEND_ROOT_STATIC)
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(FRONTEND_URL, document_root=FRONTEND_ROOT_STATIC)

django/odoo/urls.py
from django.urls import path
from . import views

app_name = "odoo"  # Opcional, pero útil para evitar conflictos de nombres

urlpatterns = [
    path(
        "tax_id/<str:tax_id_number>/", views.get_tax_id_number, name="get_tax_id_number"
    ),
    path("invoice/", views.InvoiceView.as_view(), name="invoice"),
    path(
        "invoice/validate/<int:invoice_id>/",
        views.validate_invoice,
        name="validate_invoice",
    ),
    path("expense/", views.ExpenseView.as_view(), name="expense"),
    path(
        "expense/validate/<int:expense_sheet_id>/",
        views.validate_expense_sheet,
        name="validate_expense",
    ),
    path("account_move/", views.BankAccountMoveView.as_view(), name="account_move"),
    path(
        "cash_account_move/",
        views.CashAccountMoveView.as_view(),
        name="cash_account_move",
    ),
    path(
        "delete_account_move/",
        views.delete_account_move,
        name="delete_account_move",
    ),
]

django/templates/frontend/contact.html
{% extends "base.html" %}
{% block head %}
{% endblock %}
{% block title %}
<title>GNB Contacto</title>
{% endblock %}


{% block content %}

<div class="container mt-5">
  <h1>Formulario de Contacto</h1>
  <form id="form" method="post" action="/gnb/contact/">
    {% csrf_token %}
    <!-- Agregar campos del formulario aquí -->
    <div class="mb-3">
      <label for="mensaje" class="form-label">Mensaje:</label>
      <textarea class="form-control" id="contact_msg" name="contact_msg" rows="7"></textarea>
    </div>

    <hr class="my-4">
    <button class="w-100 btn btn-primary btn-lg" type="submit">Enviar</button>
  </form>
</div>


{% endblock %}

django/templates/frontend/footer.html
<footer class="py-2 bg-black" style="margin-top: 10px; margin-bottom: 0px;">
  <div class="container px-5 d-flex justify-content-between align-items-center">
    <div>
      <p class="m-0 text-white small">
        <span id="madewith1">GNB Versión {{APP_VERSION}} <br>
        <a href="https://framagit.org/komun/gnb">Software libre</a> desarrollado por amor al hacktivismo gracias a <a href="https://komun.org">Komun SobTec</a>.
        <br><i class="text-danger bi bi-balloon-heart-fill"></i> (Donaciones en GNB al proyecto: KST)</span>
      </p>
    </div>
    <div>
      <p class="m-0 text-white text-end small">{{INVOICE_ORG_DETAILS|safe}}</p>
    </div>
  </div>
  <!-- Back to top button -->
  <button onclick="topFunction()" id="btn-back-to-top" title="Go to top"><i class="bi bi-arrow-up"></i></button>

  <!-- Extension of the footer by other templates-->
  {% block footer %}{% endblock %}

</footer>
{% block script %}{% endblock %}

django/templates/frontend/get_expense.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" href="/static/css/print.css" />

<script>
  function get_taxid_name(id) {

    var taxIdNameMap = {
      42: 'IVA 4%', 43: 'IVA 10%',
      2: 'IVA 21%', 65: 'Exportación',
      47: 'Sin IVA 0%', 19: 'Servicio intracomunitario 0%',
      35: 'IVA Exento Repercutido No Sujeto'
    };

    // Return the name for the given ID
    return taxIdNameMap[id];
  }

  function printItem() {
    var content = document.getElementById("main_card").innerHTML;
    var originalBody = document.body.innerHTML;

    document.body.innerHTML = content;

    window.print();

    document.body.innerHTML = originalBody;
  }

</script>
{% endblock %}
{% block title %}
{% endblock %}

{% block content %}

<div class="container-fluid p-0">
  <div class="alert 
    {%if object.state == 'approve' %} alert-warning
    {%elif object.state == 'draft' %} alert-secondary
    {%elif object.state == 'done' %} alert-success
    {% endif %}
  alert-dismissible" role="alert" >
      {%if object.state == 'approve' %} La Hoja de gasto está en espera de aprobación. Recibirás un correo electrónico cuando se haya aprobado.
      {%elif object.state == 'draft' %} La Hoja de gasto está en modo borrador.
      {%elif object.state == 'done' %} La Hoja de gasto está aprobada.
      {% endif %}
  </div>
</div>

<div class="card" id="main_card">
  <div class="card-body">
    <div class="container mb-5 mt-3">
      <div class="row d-flex align-items-baseline">
        <div class="col-sm-9">
            <h2>Hoja de Gasto nº {{object.name}}</h2>
            <ul class="list-unstyled">
              <li class="text-muted">
                <i class="bi bi-calendar" style="color:#84B0CA ;"></i>
                <span class="fw-bold">Fecha: </span>{{object.accounting_date}}
              </li>
            </ul>
        </div>
        <div class="no-print col-sm-3 float-end">
          <a class="btn btn-light text-capitalize border-0" data-mdb-ripple-color="dark"
            href="javascript:printItem();">
            <i class="bi bi-printer text-primary"></i> Imprimir</a>
            {% if user.is_superuser %}<a class="btn btn-light text-capitalize border-0" data-mdb-ripple-color="dark"
              href="{% url 'odoo:validate_expense' expense_sheet_id=object.id %}">
            <i class="bi bi-hand-thumbs-up-fill text-primary"></i> Aprobar y notificar</a>
            {% endif %}
        </div>
        <hr>
      </div>

      <div class="row my-2 mx-1 justify-content-center">
        <table class="table table-striped table-borderless">
          <thead style="background-color:#84B0CA ;" class="text-white">
            <tr>
              <th class="col">#</th>
              <th class="col">Descripción</th>
              <th class="col text-center">Cantidad</th>
              <th class="col text-center">Precio Unidad</th>
              <th class="col text-center">Impuestos</th>
              <th class="col text-center">Importe</th>
            </tr>
          </thead>
          <tbody>
            {% for move_line in move_lines %}
            <tr>
              <td class="fw-bold text-left">{{forloop.counter}}</td>
              <td>{{move_line.name}}</td>
              <td class="text-center">{{move_line.quantity}}</td>
              <td class="text-center">{{move_line.unit_amount}} €</td>
              <td class="text-center" id="taxNamesContainer-{{forloop.counter}}">
                {% for tax_id in move_line.tax_ids %}
                <script>
                  var taxName = get_taxid_name({{ tax_id }});
                  // Create a span element to hold the tax name
                  var spanElement = document.createElement('span');
                  spanElement.textContent = "(" + taxName + ")";
                  // Append the span to the container
                  document.getElementById('taxNamesContainer-{{forloop.parentloop.counter}}').appendChild(spanElement);

                </script>
                {% endfor %}
              </td>
              <td class="text-center">{{move_line.total_amount|floatformat:2}} €</td>
            </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>
      <div class="row float-end text-end">
        <p>
          <span class="text-black me-3"> Total Impuestos</span>
          <span style="font-size: 22px;">{{object.taxed_amount|floatformat:2}} €</span>
        </p>

        <p class="text-black ">
          <span class="text-black me-3"> Importe total</span>
          <span style="font-size: 22px;">{{object.total_amount|floatformat:2}} €</span>

        </p>

      </div>
      
    </div>
  </div>
</div>
</div>


{% endblock %}

django/templates/frontend/get_expenses.html
{% extends "base.html" %}
{% block head %}
{% endblock %}
{% block title %}
<title>GNB Tus Facturas</title>
{% endblock %}

{% block content %}


<div class="py-5 text-center">
  <h2>Mis hojas de gasto</h2>
</div>


<table id="table" data-toggle="table" data-sort-name="total" data-sort-order="desc"
  class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th data-field="numero" data-sortable="true">Número</th>
      <th data-field="fecha" data-sortable="true">Fecha</th>
      <th data-field="total" data-sortable="true">Total</th>
      <th data-field="estado" data-sortable="true">Estado</th>
    </tr>
  </thead>
  <tbody>
    {% for item in items%}
    <tr>
      <td><a href="{% url 'get_expense_sheet_view' expense_sheet_id=item.id %}">{{item.name}}</a></td>
      <td>{{item.accounting_date}}</td>
      <td>{{item.total_amount}} €</td>
      <td>{%if item.state == 'approve' %} Por aprobar
        {%elif item.state == 'draft' %} Borrador
        {%elif item.state == 'done' %} Aprobado
        {%else %}{{invoice.state}}
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% block script %}

<script>
  // Add CSS classes to the rows based on the "Estado" column value

  document.addEventListener('DOMContentLoaded', function () {
    var tableRows = document.querySelectorAll('#table tbody tr');

    tableRows.forEach(function (row) {
      var deuda = row.querySelector('td:nth-child(5)').textContent.trim();
      var estado = row.querySelector('td:nth-child(6)').textContent.trim();
      var estadoCell = row.querySelector('td:nth-child(6)');
      var estado = estadoCell.textContent.trim();
      if (estado === 'posted') {
        row.classList.add('table-success');
      } else if (estado === 'cancel') {
        row.classList.add('table-danger');
      }
      if (estado === 'posted') {
        estadoCell.textContent = 'Enviada';
      }
      if (estado === 'cancel') {
        estadoCell.textContent = 'Cancelada';
      }
      if (deuda > 0) {
        row.classList.add('table-warning');
      }

      // Add more conditions for other states if needed
    });
  });
</script>


{% endblock %}

{% endblock %}

django/templates/frontend/get_invoice.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" href="/static/css/print.css" />

<script>
  function get_taxid_name(id) {

    var taxIdNameMap = {
      42: 'IVA 4%', 43: 'IVA 10%',
      2: 'IVA 21%', 65: 'Exportación',
      47: 'Sin IVA 0%', 19: 'Servicio intracomunitario 0%',
      35: 'IVA Exento Repercutido No Sujeto'
    };

    // Return the name for the given ID
    return taxIdNameMap[id];
  }

  function printInvoice() {
    var content = document.getElementById("main_card").innerHTML;
    var originalBody = document.body.innerHTML;
    document.body.innerHTML = content;
    window.print();
    document.body.innerHTML = originalBody;
  }

</script>
{% endblock %}
{% block title %}
{% endblock %}

{% block content %}

<div class="container-fluid p-0">
  <div class="alert 
    {%if invoice.state == 'approve' %} alert-warning
    {%elif invoice.state == 'draft' %} alert-secondary
    {%elif invoice.state == 'posted' %} alert-success
    {% endif %}
  alert-dismissible" role="alert" >
  
      {%if invoice.state == 'approve' %} La factura está en espera de aprobación. Recibirás un correo electrónico cuando se haya aprobado.
      {%elif invoice.state == 'draft' %} La factura está en modo borrador.
      {%elif invoice.state == 'posted' %} La factura está aprobada{%if invoice.invoice_payment_state == 'paid' %}<b> y pagada</b>{% endif %}.
      {% endif %}
  </div>
</div>


<div class="card" id="main_card">
  <div class="card-body">
    <div class="container mb-5 mt-3">
      <div class="row d-flex align-items-baseline">
        <div class="col-sm-9">
            <h2>Factura nº {{invoice.name}}</h2>
            <ul class="list-unstyled">
              <li class="text-muted">
                <i class="bi bi-calendar" style="color:#84B0CA ;"></i>
                <span class="fw-bold">Fecha de factura: </span>{{invoice.invoice_date}}
              </li>
              <li class="text-muted">
                <i class="bi bi-calendar" style="color:#84B0CA ;"></i>
                <span class="fw-bold">Fecha de vencimiento: </span>{{invoice.invoice_date_due}}
              </li>
            </ul>
        </div>
        <div class="no-print col-sm-3 float-end">
          <a class="btn btn-light text-capitalize border-0" data-mdb-ripple-color="dark"
            href="javascript:printInvoice();">
            <i class="bi bi-printer text-primary"></i> Imprimir</a>
            {% if user.is_superuser %}<a class="btn btn-light text-capitalize border-0" data-mdb-ripple-color="dark"
              href="{% url 'odoo:validate_invoice' invoice_id=invoice.id %}">
            <i class="bi bi-hand-thumbs-up-fill text-primary"></i> Aprobar y notificar</a>
            {% endif %}
        </div>
        <hr>
      </div>

      <div class="row">
        {%if invoice.state == 'posted' %}
        <div class="col-xl-8 col-sm-6">
          <ul class="list-unstyled">
            <li class="text-muted">{{INVOICE_ORG_DETAILS|safe}}</li>
          </ul>
        </div>
        {% endif %}
        <div class="col-xl-4 col-sm-6">
          <ul class="list-unstyled">
            <li class="text-muted"> <span style="color:#5d9fc5 ;">{{partner.name}}</span></li>
            <li class="text-muted">{{partner.street}}</li>
            <li class="text-muted">{{partner.zip}}, {{partner.city}},{{partner.state_id.1}}</li>
            <li class="text-muted">Nº identif. fiscal (NIF): {{partner.vat}}</li>
          </ul>
        </div>
      </div>

      <div class="row my-2 mx-1 ms-3 justify-content-center" style="font-size: smaller;">
        <table class="table table-striped table-borderless ">
          <thead style="background-color:#84B0CA ;" class="text-white">
            <tr>
              <th class="col">Descripción</th>
              <th class="col text-center">Cantidad</th>
              <th class="col text-center">Precio Unidad</th>
              <th class="col text-center">Impuestos</th>
              <th class="col text-center">Importe</th>
            </tr>
          </thead>
          <tbody>
            {% for move_line in move_lines %}
            <tr>
              {%if move_line.display_type == "line_note" %}
                <td style="background-color: #FFFF99; text-align: center;"><i>{{move_line.name}}</i></td>
              {% else %}
                <td>{{move_line.name}}</td>
              
              <td class="text-center">{{move_line.quantity}}</td>
              <td class="text-center">{{move_line.price_unit}} €</td>
              <td class="text-center" id="taxNamesContainer-{{forloop.counter}}">
                {% for tax_id in move_line.tax_ids %}
                <script>
                  var taxName = get_taxid_name({{ tax_id }});
                  // Create a span element to hold the tax name
                  var spanElement = document.createElement('span');
                  spanElement.textContent = "(" + taxName + ")";
                  // Append the span to the container
                  document.getElementById('taxNamesContainer-{{forloop.parentloop.counter}}').appendChild(spanElement);

                </script>
                {% endfor %}
              </td>
              <td class="text-center">{{move_line.price_subtotal}} €</td>
              {% endif %}
            </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>
      <div class="row">
        <div class="col-sm-8">
          <p class="ms-3"><b>Por favor utilice la siguiente referencia al realizar su pago: {{invoice.name}}</b></p>
        </div>
        <div class="col-sm-4">
          <ul class="list-unstyled text-end mr-3">
            <li class="text-muted ms-3">
              <span class="text-black me-4">SubTotal</span>{{invoice.amount_untaxed}} €
            </li>
            {% for tax_group in invoice.amount_by_group %}
            <li class="text-right text-muted ms-3 mt-2">
              <span class="text-black me-4">{{tax_group.0}}</span>{{tax_group.1}} €
            </li>
            {% endfor %}
            <li class="text-black ms-2">
              <span class="text-black me-4">Importe total</span>{{invoice.amount_total}} €
            </li>
          </ul>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-12 text-center">
          <p>{{INVOICE_ORG_DETAILS_BELOW|safe}}</p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>


{% endblock %}

django/templates/frontend/get_invoices.html
{% extends "base.html" %}
{% block head %}
{% endblock %}
{% block title %}
<title>GNB Tus Facturas</title>
{% endblock %}

{% block content %}



<div class="py-5 text-center">
  <h2>Mis facturas</h2>
</div>


<table id="table" data-toggle="table" data-sort-name="total" data-sort-order="desc"
  class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th data-field="fecha" data-sortable="true">Fecha</th>
      <th data-field="numero" data-sortable="true">Número</th>
      <th data-field="cliente" data-sortable="true">Cliente</th>
      <th data-field="total" data-sortable="true">Total</th>
      <th data-field="adeudado" data-sortable="true">Adeudado</th>
      <th data-field="estado" data-sortable="true">Estado</th>
    </tr>
  </thead>
  <tbody>
    {% for invoice in items%}
    <tr>
      <td>{{invoice.invoice_date}}</td>
      <td><a href="{% url 'get_invoice_view' invoice_id=invoice.id %}">
        {%if invoice.name == "/" %}{{CURRENT_YEAR}}/{{invoice.project_code}}/Pendiente
        {%else %}{{invoice.name}}{% endif %}</a></td>
      <td>{{invoice.partner_id.1}}</td>
      <td>{{invoice.amount_total_signed}}</td>
      <td>{{invoice.amount_residual_signed}}</td>
      <td>{%if invoice.state == 'posted' and invoice.invoice_payment_state == 'paid' %}Pagada
        {%elif invoice.state == 'posted' %} Aprobada
        {%elif invoice.state == 'draft' %} Borrador
        {%else %}{{invoice.state}}
        {% endif %}
      </td>
      <td></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% block script %}

<script>
  // Add CSS classes to the rows based on the "Estado" column value

  document.addEventListener('DOMContentLoaded', function () {
    var tableRows = document.querySelectorAll('#table tbody tr');

    tableRows.forEach(function (row) {
      var deuda = row.querySelector('td:nth-child(5)').textContent.trim();
      var estado = row.querySelector('td:nth-child(6)').textContent.trim();
      var estadoCell = row.querySelector('td:nth-child(6)');
      var estado = estadoCell.textContent.trim();
      if (estado === 'posted') {
        row.classList.add('table-success');
      } else if (estado === 'cancel') {
        row.classList.add('table-danger');
      }
      if (estado === 'posted') {
        estadoCell.textContent = 'Enviada';
      }
      if (estado === 'cancel') {
        estadoCell.textContent = 'Cancelada';
      }
      if (deuda > 0) {
        row.classList.add('table-warning');
      }

      // Add more conditions for other states if needed
    });
  });
</script>


{% endblock %}

{% endblock %}

django/templates/frontend/menu.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container px-5 text-white">
    <a class="navbar-brand" href="/"><img class="img-fluid rounded-3 my-5" src="/static/assets/images/logo.png"
        alt="Logotipo GNB, que se identifica con un suricato con la mano abierta mostrando las letras GNB" /></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
        class="navbar-toggler-icon"></span></button>
    <div class="ms-auto mb-2 mb-lg-0" id="username_navbar">
      {% if user.is_superuser %}
      <span>Actuando como usuario:</span>
      <select class="selectpicker" id="user_selector" data-live-search="true">
        <option value="----">------</option>
        {% for u in all_users %}
        <option value="{{ u.id }}" {% if u.id == user_id %}selected="selected" {% endif %}>{{ u.username }}</option>
        {% endfor %}
      </select>
      {% else %}
      Hola {{ user.username }}
      {% endif %}
      <script>
        const userSelector = document.getElementById("user_selector");
        userSelector.addEventListener("change", function () {
          const selectedUserId = this.value;
          const currentUrlWithoutParams = window.location.href.split('?')[0];
          const newUrl = `${currentUrlWithoutParams}?user=${selectedUserId}`;
          window.location.href = newUrl;
        });
      </script>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " href="{% url 'my_dashboard_view' %}{%if user_id %}?user={{user_id}}{%endif%}">Panel</a>
        </li>
        <li class="nav-item">
          <a class="nav-link "
            href="{% url 'get_invoices_view' %}{%if user_id %}?user={{user_id}}{%endif%}">Facturas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'get_expenses_view' %}{%if user_id %}?user={{user_id}}{%endif%}">Gastos</a>
        </li>

        {% if user.is_superuser %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle show align-items-center" href="#" id="my_account" data-bs-toggle="dropdown"
            aria-expanded="false">
            Administración</a>
          <ul class="dropdown-menu" aria-labelledby="my_account" data-bs-popper="none">
            <li><a class="nav-link text-black" href="{% url 'new_cashin_view' %}">Añadir Ingreso</a></li>
            <li><a class="nav-link text-black" href="{% url 'new_project_view' %}">Nuevo Proyecto</a></li>
            <li><a class="nav-link text-black" href="{% url 'new_user_view' %}">Nuev@ Usuari@</a></li>
            <li><a class="nav-link text-black" href="{% url 'users_report_view' %}">Balances Usuarios</a></li>
            <li><a class="nav-link text-black" href="{% url 'projects_report_view' %}">Balances Proyectos</a></li>

            <li><a class="nav-link text-black" href="/admin/">Backend</a></li>
          </ul>
        </li>
        {% endif %}


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle show align-items-center" style="margin-top:-7px" href="#" id="my_account"
            data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-circle fs-3"></i></a>

          <ul class="dropdown-menu" aria-labelledby="my_account" data-bs-popper="none">
            <li><a class="nav-link text-black" href="{% url 'contact_view' %}">Contacto</a></li>
            <li><a class="nav-link text-black" href="{% url 'logout' %}">Desconectarse</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

django/templates/frontend/portal_logged_in.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>


<div class="container">
  <!-- Aquí puedes agregar el contenido de tu página -->
  <h1>Bienvenid@ a GNB</h1>
</div>
</body>

</html>

django/templates/frontend/portal_logged_out.html
<center>
  <img src="/static/assets/images/logo.png" />
  <br>
  <h2 class="mt-3"> Bienvenid@ a GNB, debes <a class="centered-button" href="/accounts/login/">iniciar sesión</a>.</h2>
</center>